apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    controller-tools.k8s.io: "1.0"
  name: functions.openwhisk.seed.ibm.com
spec:
  group: openwhisk.seed.ibm.com
  names:
    kind: Function
    plural: functions
    shortNames:
    - owf
  scope: Namespaced
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          type: string
        kind:
          type: string
        metadata:
          type: object
        spec:
          properties:
            annotations:
              items:
                properties:
                  attributes:
                    type: object
                  name:
                    type: string
                  valueFrom:
                    properties:
                      configMapKeyRef:
                        type: object
                      secretKeyRef:
                        type: object
                    type: object
                required:
                - name
                type: object
              type: array
            code:
              type: string
            codeURI:
              type: string
            context:
              properties:
                org:
                  type: string
                region:
                  type: string
                resourcegroup:
                  type: string
                resourcelocation:
                  type: string
                space:
                  type: string
              required:
              - org
              - space
              - region
              - resourcegroup
              - resourcelocation
              type: object
            contextFrom:
              type: object
            docker:
              type: string
            functions:
              type: string
            limits:
              properties:
                logSize:
                  format: int64
                  type: integer
                memory:
                  format: int64
                  type: integer
                timeout:
                  format: int64
                  type: integer
              type: object
            main:
              type: string
            name:
              type: string
            native:
              type: boolean
            package:
              type: string
            parameters:
              items:
                properties:
                  attributes:
                    type: object
                  name:
                    type: string
                  valueFrom:
                    properties:
                      configMapKeyRef:
                        type: object
                      secretKeyRef:
                        type: object
                    type: object
                required:
                - name
                type: object
              type: array
            rawHTTP:
              type: boolean
            runtime:
              type: string
            webExport:
              type: boolean
          required:
          - runtime
          type: object
        status:
          properties:
            generation:
              format: int64
              type: integer
            message:
              type: string
            state:
              type: string
          required:
          - generation
          type: object
  version: v1beta1
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
