language: go
go:
  - "1.11.x"
dist: xenial
sudo: required
services:
  - docker
branches:
  only:
  - master
  - /^v\d+\.\d+(\.\d+)?(-\S*)?$/

go_import_path: github.com/ibm/cloud-functions-operator

before_install:
  - ./tools/travis/start-kubeadm-dind.sh
  - ./tools/travis/k8s-tools.sh
  - ./tools/travis/minikube-install.sh
  - ./tools/travis/bx-install.sh
  - ./tools/travis/bx-setup.sh
  - go get -v github.com/onsi/ginkgo/ginkgo

jobs:
  include:
    - stage: test
      script: make test
      env:
      - REMOTE_OPENWHISK=1 INSTALL_IBMCLOUD=1 INSTALL_K8S_TOOLS=1
    - script: test/e2e/test-install.sh
      env:
      - INSTALL_MINIKUBE=1 INSTALL_K8S_TOOLS=1
    - script: test/e2e/test.sh
      env:
      - REMOTE_OPENWHISK=1 INSTALL_IBMCLOUD=1 INSTALL_K8S_TOOLS=1 INSTALL_MINIKUBE=1 KUBE_ENV=local
    - stage: deploy
      script: bash tools/travis/docker.sh
      skip_cleanup: true
      if: (branch = master AND type = push) OR tag =~ ^v