language: go
go:
  - "1.11.x"
dist: xenial
sudo: required
services:
  - docker
  
go_import_path: github.com/ibm/openwhisk-operator

before_install:
  - ./tools/travis/start-kubeadm-dind.sh
  - ./tools/travis/k8s-tools.sh
  - ./tools/travis/minikube-install.sh
  - ./tools/travis/bx-install.sh
  - ./tools/travis/bx-setup.sh
  - if [ ! -z "$RUN_DEP" ]; then curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh ; fi
  - go get -v github.com/onsi/ginkgo/ginkgo
  
install:
  - if [ ! -z "$RUN_DEP" ]; then dep ensure -v; fi
  
jobs:
  include:
    - stage: test
      script: make test      
      env:
      - KB_VERSION=1.0.5 REMOTE_OPENWHISK=1 INSTALL_IBMCLOUD=1 INSTALL_K8S_TOOLS=1 RUN_DEP=1 
    - script: test/e2e/test-install.sh
      env:
      - INSTALL_MINIKUBE=1 INSTALL_K8S_TOOLS=1
    - script: test/e2e/test.sh
      env:
      - REMOTE_OPENWHISK=1 INSTALL_IBMCLOUD=1 INSTALL_K8S_TOOLS=1 INSTALL_MINIKUBE=1 RUN_DEP=1 KUBE_ENV=local
    - stage: deploy
      script: bash tools/travis/docker.sh
      env:
      - RUN_DEP=1 
      skip_cleanup: true
      if: branch = master OR env(TRAVIS_TAG) 
 