language: go
go:
  - "1.11.x"
dist: trusty
sudo: required
services:
  - docker
  
go_import_path: github.com/ibm/openwhisk-operator

before_install:
  - curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
  - ./tools/travis/k8s-tools.sh
  - ./tools/travis/minikube-install.sh
  - ./tools/travis/bx-install.sh
  - ./tools/travis/bx-setup.sh
  - go get -v github.com/onsi/ginkgo/ginkgo
  
install:
  - dep ensure -v
  
jobs:
  include:
    - stage: test
      script: make test      
      env:
      - KB_VERSION=1.0.5
    # - script: test/e2e/install-local.sh
    #  env:
    #    INSTALL_MINIKUBE=true 
    - stage: deploy
      script: bash tools/travis/docker.sh
      skip_cleanup: true
      if: branch = master OR env(TRAVIS_TAG) 
 