apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    controller-tools.k8s.io: "1.0"
  name: rules.openwhisk.seed.ibm.com
spec:
  group: openwhisk.seed.ibm.com
  names:
    kind: Rule
    plural: rules
    shortNames:
    - owr
  scope: Namespaced
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          type: string
        kind:
          type: string
        metadata:
          type: object
        spec:
          properties:
            contextFrom:
              type: object
            function:
              type: string
            name:
              type: string
            trigger:
              type: string
          required:
          - trigger
          - function
          type: object
        status:
          properties:
            generation:
              format: int64
              type: integer
            message:
              type: string
            state:
              type: string
          required:
          - generation
          type: object
  version: v1beta1
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
