apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    controller-tools.k8s.io: "1.0"
  name: triggers.openwhisk.seed.ibm.com
spec:
  group: openwhisk.seed.ibm.com
  names:
    kind: Trigger
    plural: triggers
    shortNames:
    - owt
  scope: Namespaced
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          type: string
        kind:
          type: string
        metadata:
          type: object
        spec:
          properties:
            annotations:
              items:
                properties:
                  attributes:
                    type: object
                  name:
                    type: string
                  valueFrom:
                    properties:
                      configMapKeyRef:
                        type: object
                      secretKeyRef:
                        type: object
                    type: object
                required:
                - name
                type: object
              type: array
            contextFrom:
              type: object
            feed:
              type: string
            name:
              type: string
            parameters:
              items:
                properties:
                  attributes:
                    type: object
                  name:
                    type: string
                  valueFrom:
                    properties:
                      configMapKeyRef:
                        type: object
                      secretKeyRef:
                        type: object
                    type: object
                required:
                - name
                type: object
              type: array
          type: object
        status:
          properties:
            generation:
              format: int64
              type: integer
            message:
              type: string
            state:
              type: string
          required:
          - generation
          type: object
  version: v1beta1
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
